language: node_js

cache: yarn

script: ""

deploy:
  - provider: npm
    email:
      secure: KkM7cY/LrJw/XdOK9obUPjmsxM0IUegEefsAt/gIfl6s1MMH6/+D+d6COBSGwug5GDn1n301NvsSyzLeS/kfK/m371CzF6YB5J6HwL+sFnjxSGR/Odr7GT3LimZJAvOQBUTMnIrJitvThO2zZ0KDtKNoUz2xXVwWxjcP2ewe3Eh6DltsT6hKnehHd9xBLqC3SHaSi2XP+nkP8mmEF5idvefEm9XpbZ4o222nVHy+anC2lbyDbzAsRxAb+ZhwqTGHWLBFuarkL5Uy2DjmxTNh3jx2WsXSPOAxoZY1YborkzbuykW0ABz0LlFxPCnBOmCKlP4qPNPA51zBixRK04CUIpKmnfYk6cQp1AamaVxrfU22xFcKyBxp5ENEyNY84x8l7VC69vivUtQv14ttw7toln9F4aAbpdBXe1nPhdzaaNAcylt/XfnfAM7FqGhYz1ILa3Dh0xs/t3hxrJskZ6WQ2gPLD5ecATs3RJPmEau3ayrvahU0xXEljV0/sp6WJJJ/Ew42id+oS9MkJaY+0sEcoeTKNjB2hHx2/JB1AioXDPZvMYK23/l6m667a+0eFBX9zAfuGwzHsr/ho7bVIFw/uhAagJBrLxUQLxOzc3S6sIodVc5jHUOUyCGlFNnJLt3C3KV65rCgoLLl/eISOpiRzrBIps+ScQNyR40EIpIadc0=
    api_key:
      secure: UJUelv7cjEousOnTRLbA9HcG56BaTwM1QNoklIJ9CwdkmXWBzS3AKDAcoq377sgwLivSYhu468PbzIW6q7nmKlR+BMa/UuUsw8qN8LMQ4N5Pa1wq8IZg1hY1pOjKX2OKTYbkYxisUxSlXbfm64c/zv2F1R8vFgHd9N6H85TZCrTRrjxkLzrigv0E/JBTAnbdczBAhqQycG/XtvAyUeIref+b0xCRZeIpUFYWijB8pZPVz2j+FAcHP0oxHDVr5QfkbHoCosLDTNrzh4NCmAdot6wPbJTvFcIUhUVKuJ7f6C+wv0iaLybpZKpgz3Vd66cXye6iByDBhCLBElGaDDoVK1D3yrNCE9Kbn8FUsKdk+A4IAqPaAm2DXXWx/jbcjBi1jtl4UipYIz83byBYksfK77n8k9yYGtaezW2TLtZChH0DQr577zBTflkIbQ31i0i79s28TkNJzlb2ZWpqmqHaPHz6isKQWYnQ8OYRmQrCtiOqqiRkFQ5EnBwrGL+Xa75L2jsxWW5Cke85xYwF03pqkZFB5m6cTsrSBYfK0nl9CAYW1kjmhABLmrtfjMLHMdYw0cpLzHYigaF3lns9TKVPmdy79fu5U1Lq3AfSC0N1V/N+gKF2ZUh9jXOak2udeWRky7KP3Z8+XxyJNZoZ/S1sTTZmLH2O7oEpHytwrb71TY4=
    on:
      tags: true
