jobs:
  fast_finish: true
  include:
    - stage: build
      install: docker build --tag ci .ci
      script: docker run --init --rm --mount type=bind,source="${PWD}",target=/app ci
      os: linux
      dist: xenial
      language: generic
      services:
        - docker

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key:
      secure: "G/0PP9HWMOiN5LVY928X9ufL4KJSlxZNa+Zuldvn2VxTqy37ap2ztGj+mxvx2spbmq29GbyjHA2SMANFbxlU64Lm0SUJYJMINKRD422gkhga7xqIoCdsvNycOGSZkGQwEAXwWzs7e+B1v4MiOBBZ/A9R+22yAXTJVxURQuvXHVTh27qlyHIcTxytGdrRcI3UjMnW3C0DneC2UUtC150jRWBnv3DxcHqzVeIwIsScslhFcLZxz7FK1LfFw3dX1hCTG5PjgjPslAyBSUgnRIasRm9grB2qF2Lxwn4569rYooL37jg6SYCLYJ3CGGLjFPFPLlzgxpjsA5Hjtx+d4JvdA7vdnaq3Rs5p0O52RgywS6B/MTGfsx3zfDD3QTrIUoa8Llv+6Fl+rCdz0yMLtP8Nai2rwu8ZIHTBcZadxZDC1/flPk3zYANmw3rruUmkANFR9NyOUDWCNJHCp72/Bvf/ODiWkbCNAresKgcaSxdBfE7CZB7LV9GlKDKQsmJAoPB4PFqKC5ITQxPgCoz8eCLu60WEDH+Gu3e/QEgsYwc+7jY1bEwWAoXNn4bVCBJBrFw0baFz9uVkJytGpufUeYfAbenVyZ3WrE/40rNJqGqeIGS8oKM5cjBBhfP5zNO5ITYcz0LkzGjkIpp51RbDHiUr6I2JUdQRzdDydP33lRmjjtE="
    skip_cleanup: true
    on:
      tags: true
